# Generated by Django 4.0.7 on 2023-04-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to='resumes/'),
        ),
    ]
