# Generated by Django 4.0.7 on 2023-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disc_flag',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='disc_section',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDescription',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseMarkHW',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseSection',
            field=models.CharField(max_length=30),
        ),
    ]
