# Generated by Django 3.2.12 on 2023-05-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
