# Generated by Django 3.2.12 on 2023-05-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
