# Generated by Django 4.0.7 on 2023-04-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_related_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='related_course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='main.course'),
        ),
    ]
