# Generated by Django 4.1.7 on 2023-04-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_semester_application_status_course_filled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='total_postitions',
            new_name='total_positions',
        ),
    ]
