# Generated by Django 4.0.7 on 2023-03-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_disc_flag_course_disc_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseDate',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseDescription',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseEndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseMarkHW',
            new_name='graded_hw',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseInstructor',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseNumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseOfficeHours',
            new_name='office_hours',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseTANeeded',
            new_name='positions',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseSection',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseStartTime',
            new_name='start_time',
        ),
    ]
