# Generated by Django 3.2.12 on 2023-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
