# Generated by Django 4.0.7 on 2023-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Unavailable', 'Unavailable'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Open', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Hired', 'Hired')], default='available', max_length=10),
        ),
    ]
