# Generated by Django 4.0.7 on 2023-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_status_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Unavailable', 'Unavailable'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Available', max_length=15),
        ),
    ]
