# Generated by Django 4.0.7 on 2023-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
